# Generated by Django 5.2.4 on 2025-07-27 02:46

import django.db.models.deletion
import django.utils.timezone
import myapp1.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', myapp1.fields.DefaultTodayField(blank=True, default=django.utils.timezone.localdate, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', myapp1.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('last_name', myapp1.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('date_added', myapp1.fields.DefaultTodayField(blank=True, default=django.utils.timezone.localdate, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', myapp1.fields.MonthYearField(blank=True, default=django.utils.timezone.now, help_text='Format: MM/YYYY', null=True)),
                ('beginning_balance', myapp1.fields.AmountField(decimal_places=2, max_digits=10)),
                ('ending_balance', myapp1.fields.AmountField(decimal_places=2, max_digits=10)),
                ('cash_on_hand', myapp1.fields.AmountField(decimal_places=2, max_digits=10)),
                ('cash_on_bank', myapp1.fields.AmountField(decimal_places=2, max_digits=10)),
                ('created_at', myapp1.fields.AutoCreatedAtField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', myapp1.fields.ShortCharField(blank=True, default='', max_length=50, unique=True)),
                ('value', myapp1.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('description', myapp1.fields.MediumCharField(blank=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', myapp1.fields.ShortCharField(blank=True, default='', max_length=50)),
                ('created_at', myapp1.fields.AutoCreatedAtField(auto_now_add=True)),
                ('collection_list', myapp1.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.collectionlist')),
                ('member', myapp1.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', myapp1.fields.MonthYearField(blank=True, default=django.utils.timezone.now, help_text='Format: MM/YYYY', null=True)),
                ('collection', myapp1.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.collection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', myapp1.fields.DefaultTodayField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('amount', myapp1.fields.AmountField(decimal_places=2, max_digits=10)),
                ('notes', myapp1.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('report', myapp1.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.report')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='collectionlist',
            name='report',
            field=myapp1.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.report'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', myapp1.fields.DefaultTodayField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('amount', myapp1.fields.AmountField(decimal_places=2, max_digits=10)),
                ('to_bank', myapp1.fields.DefaultBooleanField(True)),
                ('notes', myapp1.fields.LongCharField(blank=True, default='', max_length=1023)),
                ('report', myapp1.fields.CascadeRequiredForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
