# Generated by Django 5.2.4 on 2025-07-27 02:58

import django.db.models.deletion
import django.utils.timezone
import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlist',
            name='report',
            field=myapp1.fields.CascadeOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp1.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='month_year',
            field=myapp1.fields.MonthYearField(blank=True, default=django.utils.timezone.now, help_text='Format: MM/YYYY', null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('first_name', 'last_name')},
        ),
    ]
