# Generated by Django 5.2.4 on 2025-07-28 01:06

import django.utils.timezone
import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_alter_collectionlist_report_alter_report_month_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionlist',
            name='collection_date',
            field=myapp1.fields.DefaultTodayField(blank=True, default=django.utils.timezone.localdate, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='collectionmonth',
            name='month',
            field=myapp1.fields.MonthYearField(blank=True, default=myapp1.fields.default_month_start, help_text='Format: YYYY-MM', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='month_year',
            field=myapp1.fields.MonthYearField(blank=True, default=myapp1.fields.default_month_start, help_text='Format: YYYY-MM', null=True, unique=True),
        ),
    ]
