# Generated by Django 5.2.4 on 2025-07-28 01:23

import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_collectionlist_collection_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=myapp1.fields.DefaultBooleanField(True),
        ),
    ]
