# Generated by Django 5.2.4 on 2025-07-28 01:58

import django.db.models.deletion
import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_member_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='member',
            field=myapp1.fields.SetNullOptionalForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp1.member'),
        ),
    ]
