# Generated by Django 5.2.4 on 2025-07-28 04:09

import django.db.models.deletion
import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_alter_collection_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_list',
            field=myapp1.fields.CascadeOneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.collectionlist'),
        ),
    ]
