# Generated by Django 5.2.4 on 2025-07-28 06:15

import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_alter_collection_collection_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='amount',
            field=myapp1.fields.AmountField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='end_month',
            field=myapp1.fields.MonthYearField(blank=True, default=myapp1.fields.default_month_start, help_text='Format: YYYY-MM', null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='start_month',
            field=myapp1.fields.MonthYearField(blank=True, default=myapp1.fields.default_month_start, help_text='Format: YYYY-MM', null=True),
        ),
        migrations.DeleteModel(
            name='CollectionMonth',
        ),
    ]
