# Generated by Django 5.2.4 on 2025-07-28 06:46

import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_collection_amount_collection_end_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='receipt_number',
            field=myapp1.fields.ShortCharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
