# Generated by Django 5.2.4 on 2025-07-28 08:57

import django.utils.timezone
import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0008_alter_collection_receipt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_list',
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_date',
            field=myapp1.fields.DefaultTodayField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.DeleteModel(
            name='CollectionList',
        ),
    ]
