# Generated by Django 5.2.4 on 2025-07-28 10:46

import django.utils.timezone
import myapp1.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_remove_collection_collection_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', myapp1.fields.DefaultTodayField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('amount', myapp1.fields.AmountField(decimal_places=2, max_digits=10)),
                ('notes', myapp1.fields.LongCharField(blank=True, default='', max_length=1023)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='expense',
            name='report',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='report',
        ),
    ]
