# Generated by Django 5.2.4 on 2025-07-28 13:40

import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0010_income_remove_expense_report_remove_transfer_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='cash_on_bank',
            new_name='beginning_cash_on_bank',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='cash_on_hand',
            new_name='beginning_cash_on_hand',
        ),
        migrations.AddField(
            model_name='report',
            name='ending_cash_on_bank',
            field=myapp1.fields.AmountField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='ending_cash_on_hand',
            field=myapp1.fields.AmountField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
