# Generated by Django 5.2.4 on 2025-07-28 14:06

import myapp1.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0011_rename_cash_on_bank_report_beginning_cash_on_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='bank_additions',
            field=myapp1.fields.AmountField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='hand_additions',
            field=myapp1.fields.AmountField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
